import type { FactionInfo } from "./types";

export const FACTIONS: FactionInfo[] = [

  // ================= 구파일방 =================

  {
    name: "화산파",
    group: "구파일방",
    style: "검 밸런스 / 속도",
    summary: "날카롭고 빠른 검로를 추구하는 정통 검문.",
    expBonus: 2,
    coinBonus: 0,
    touchFlavor: "매화 잎처럼 빠른 검격으로 허수아비를 연속 타격합니다.",
    theme: { glow: "rgba(255,120,120,0.22)", accent: "#ffb3b3" },
    bonusStats: { atk: 15, critRate: 15, critDmg: 15, speed: 10 },
    characterImages: { ready: "/images/char_hwasan_ready.png", attack: "/images/char_hwasan_attack.png" },
    specialAdvantage: "치명타 시 추가 검기 발동, 3연타 시 4번째 공격 2배 위력",
    martial: {
      필부: { name: "기초검식", innerPower: "-", stats: { atk: 5 } },
      삼류: { name: "매화초식", innerPower: "2년", stats: { atk: 15, critRate: 3 } },
      이류: { name: "낙화검법", innerPower: "8년", stats: { atk: 40, critRate: 5, critDmg: 5 } },
      일류: { name: "비화검결", innerPower: "24년", stats: { atk: 120, critRate: 8, critDmg: 10, speed: 5 } },
      절정: { name: "매화십이검", innerPower: "50년", stats: { atk: 350, critRate: 12, critDmg: 20, speed: 10 } },
      초절정: { name: "홍매검극", innerPower: "120년", stats: { atk: 1200, critRate: 15, critDmg: 35, speed: 15 } },
      화경: { name: "적화검강", innerPower: "200년", stats: { atk: 4000, critRate: 20, critDmg: 60, speed: 20 } },
      현경: { name: "화산진혼검", innerPower: "320년", stats: { atk: 15000, critRate: 25, critDmg: 100, speed: 30 } },
      생사경: { name: "매화멸혼검", innerPower: "450년", stats: { atk: 50000, critRate: 30, critDmg: 180, speed: 40 } },
      신화경: { name: "천화검령", innerPower: "600년", stats: { atk: 180000, critRate: 40, critDmg: 300, speed: 60 } },
      천인합일: { name: "무극매화검", innerPower: "1000년", stats: { atk: 700000, critRate: 50, critDmg: 500, speed: 100 } },
    },
    movement: { entry: "매화보", peak: "홍화비연보", final: "천화유영보" },
  },

  {
    name: "소림",
    group: "구파일방",
    style: "탱커 / 금강",
    summary: "권과 장을 기반으로 몸과 기초를 단단히 다지는 정통 불문 수련.",
    expBonus: 1,
    coinBonus: 0,
    touchFlavor: "묵직한 정권과 장력으로 허수아비를 흔들어 놓습니다.",
    theme: { glow: "rgba(255,210,120,0.22)", accent: "#ffe39d" },
    bonusStats: { def: 40, hp: 30, atk: 10 },
    characterImages: { ready: "/images/char_shaolin_ready.png", attack: "/images/char_shaolin_attack.png" },
    specialAdvantage: "피해 감소 고정 적용, 현재 체력 비율이 높을수록 공격력 추가 증가",
    martial: {
      필부: { name: "기초권", innerPower: "-", stats: { def: 10, hp: 50 } },
      삼류: { name: "나한권", innerPower: "2년", stats: { def: 30, hp: 150, atk: 5 } },
      이류: { name: "복호권", innerPower: "8년", stats: { def: 80, hp: 450, atk: 15 } },
      일류: { name: "금강권", innerPower: "24년", stats: { def: 250, hp: 1500, atk: 50 } },
      절정: { name: "나한십팔수", innerPower: "50년", stats: { def: 800, hp: 5000, atk: 150 } },
      초절정: { name: "금강불괴권", innerPower: "120년", stats: { def: 2500, hp: 16000, atk: 500 } },
      화경: { name: "대력금강장", innerPower: "200년", stats: { def: 10000, hp: 50000, atk: 1500 } },
      현경: { name: "무상금강체", innerPower: "320년", stats: { def: 40000, hp: 200000, atk: 5000 } },
      생사경: { name: "불멸나한신공", innerPower: "450년", stats: { def: 150000, hp: 800000, atk: 15000 } },
      신화경: { name: "여래신장", innerPower: "600년", stats: { def: 600000, hp: 3000000, atk: 50000 } },
      천인합일: { name: "대각여래진", innerPower: "1000년", stats: { def: 2500000, hp: 15000000, atk: 150000 } },
    },
    movement: { entry: "나한보", peak: "금강비천보", final: "여래무영보" },
  },

  {
    name: "무당",
    group: "구파일방",
    style: "카운터 / 태극",
    summary: "태극과 내공을 중심으로 유연하게 흘리며 되받아치는 도가 무학.",
    expBonus: 1,
    coinBonus: 1,
    touchFlavor: "흘리고 되받아치는 태극의 흐름으로 타격이 이어집니다.",
    theme: { glow: "rgba(160,220,255,0.22)", accent: "#bde7ff" },
    bonusStats: { eva: 45, speed: 20, atk: 5 },
    characterImages: { ready: "/images/char_wudang_ready.png", attack: "/images/char_wudang_attack.png" },
    specialAdvantage: "회피 성공 시 다음 공격 대폭 강화, 장기전 비례 대미지 상승, 회피 시 즉시 반격",
    martial: {
      필부: { name: "양의호흡", innerPower: "-", stats: { eva: 5, speed: 2 } },
      삼류: { name: "태극기공", innerPower: "2년", stats: { eva: 8, speed: 5 } },
      이류: { name: "운수권", innerPower: "8년", stats: { eva: 12, speed: 8, def: 10 } },
      일류: { name: "태극검", innerPower: "24년", stats: { eva: 15, speed: 12, def: 50, atk: 20 } },
      절정: { name: "태극십삼세", innerPower: "50년", stats: { eva: 20, speed: 15, def: 200, atk: 100 } },
      초절정: { name: "무극검식", innerPower: "120년", stats: { eva: 25, speed: 20, def: 1000, atk: 500 } },
      화경: { name: "태극진기", innerPower: "200년", stats: { eva: 30, speed: 30, def: 5000, atk: 2000 } },
      현경: { name: "음양합일공", innerPower: "320년", stats: { eva: 35, speed: 45, def: 25000, atk: 8000 } },
      생사경: { name: "태허귀원공", innerPower: "450년", stats: { eva: 40, speed: 60, def: 120000, atk: 30000 } },
      신화경: { name: "무극천도", innerPower: "600년", stats: { eva: 50, speed: 80, def: 500000, atk: 120000 } },
      천인합일: { name: "태극자연체", innerPower: "1000년", stats: { eva: 70, speed: 120, def: 2200000, atk: 500000 } },
    },
    movement: { entry: "운보", peak: "태극유운보", final: "무극무형보" },
  },

  {
    name: "개방",
    group: "구파일방",
    style: "실전 생존 / 신개",
    summary: "거칠고 자유로운 실전 감각으로 싸우는 거리의 무학.",
    expBonus: 1,
    coinBonus: 2,
    touchFlavor: "흐트러진 동작 속에서 의외의 강타가 튀어나옵니다.",
    theme: { glow: "rgba(255,210,150,0.2)", accent: "#ffd7ab" },
    bonusStats: { eva: 35, critRate: 15, speed: 10, hp: 10 },
    characterImages: { ready: "/images/char_gaebang_ready.png", attack: "/images/char_gaebang_attack.png" },
    specialAdvantage: "남은 체력이 낮을수록 회피율 증가, 일정 확률로 비정형적인 강력한 추가타 발생",
    martial: {
      필부: { name: "난타술", innerPower: "-", stats: { atk: 3, eva: 2 } },
      삼류: { name: "취권", innerPower: "2년", stats: { atk: 12, eva: 8 } },
      이류: { name: "타구봉법", innerPower: "8년", stats: { atk: 35, eva: 15 } },
      일류: { name: "항룡장", innerPower: "24년", stats: { atk: 150, eva: 22, critRate: 5 } },
      절정: { name: "항룡십팔장", innerPower: "50년", stats: { atk: 450, eva: 30, critRate: 10 } },
      초절정: { name: "강룡십팔장", innerPower: "120년", stats: { atk: 1800, eva: 40, critRate: 15 } },
      화경: { name: "용격장", innerPower: "200년", stats: { atk: 6000, eva: 50, critRate: 20 } },
      현경: { name: "항룡파천", innerPower: "320년", stats: { atk: 25000, eva: 65, critRate: 30 } },
      생사경: { name: "강룡멸살", innerPower: "450년", stats: { atk: 90000, eva: 85, critRate: 45 } },
      신화경: { name: "용격귀일", innerPower: "600년", stats: { atk: 400000, eva: 120, critRate: 70 } },
      천인합일: { name: "용신강림", innerPower: "1000년", stats: { atk: 1500000, eva: 200, critRate: 120 } },
    },
    movement: { entry: "취개보", peak: "걸인신법", final: "용영비행" },
  },

  {
    name: "청성파",
    group: "구파일방",
    style: "암살 / 속검",
    summary: "빠르고 은밀한 움직임으로 급소를 노리는 검파.",
    expBonus: 1,
    coinBonus: 1,
    touchFlavor: "잔상이 남는 빠른 검격이 스쳐 지나갑니다.",
    theme: { glow: "rgba(180,255,180,0.18)", accent: "#c8f7c8" },
    bonusStats: { critRate: 40, eva: 15, speed: 15 },
    characterImages: { ready: "/images/char_cheongseong_ready.png", attack: "/images/char_cheongseong_attack.png" },
    specialAdvantage: "전투 시작 후 첫 공격 필살급 강화, 회피 성공 후 치명타 확률 폭증, 5% 확률로 10배 피해(약점간파)",
    martial: {
      필부: { name: "기초검", innerPower: "-", stats: { critRate: 3 } },
      삼류: { name: "청성검", innerPower: "2년", stats: { critRate: 8, atk: 5 } },
      이류: { name: "비영검", innerPower: "8년", stats: { critRate: 15, atk: 20 } },
      일류: { name: "청풍검법", innerPower: "24년", stats: { critRate: 25, atk: 80, eva: 5 } },
      절정: { name: "청성십삼검", innerPower: "50년", stats: { critRate: 40, atk: 300, eva: 10 } },
      초절정: { name: "비영절명검", innerPower: "120년", stats: { critRate: 60, atk: 1000, eva: 15 } },
      화경: { name: "청풍무형검", innerPower: "200년", stats: { critRate: 90, atk: 3500, eva: 25 } },
      현경: { name: "청성귀일", innerPower: "320년", stats: { critRate: 150, atk: 12000, eva: 40 } },
      생사경: { name: "청성멸혼검", innerPower: "450년", stats: { critRate: 250, atk: 40000, eva: 60 } },
      신화경: { name: "청성천검", innerPower: "600년", stats: { critRate: 500, atk: 150000, eva: 100 } },
      천인합일: { name: "무형청풍검", innerPower: "1000년", stats: { critRate: 1000, atk: 600000, eva: 180 } },
    },
    movement: { entry: "청풍보", peak: "비영신법", final: "무형풍신보" },
  },

  {
    name: "점창파",
    group: "구파일방",
    style: "초고속 / 연타",
    summary: "빛처럼 빠른 검로를 사용하는 검파.",
    expBonus: 2,
    coinBonus: 0,
    touchFlavor: "눈에 보이지 않는 속도로 연속 타격합니다.",
    theme: { glow: "rgba(255,255,180,0.18)", accent: "#ffffcc" },
    bonusStats: { speed: 50, critRate: 25, atk: 10 },
    characterImages: { ready: "/images/char_jeomchang_ready.png", attack: "/images/char_jeomchang_attack.png" },
    specialAdvantage: "기본 공격 연속 횟수 증가, 공격 연속 명중 시 치명타 확률 실시간 무한 누적",
    martial: {
      필부: { name: "기초검", innerPower: "-", stats: { speed: 5 } },
      삼류: { name: "점창검", innerPower: "2년", stats: { speed: 15, critRate: 2 } },
      이류: { name: "속검술", innerPower: "8년", stats: { speed: 40, critRate: 5 } },
      일류: { name: "유광검법", innerPower: "24년", stats: { speed: 100, critRate: 10, atk: 20 } },
      절정: { name: "점창연환검", innerPower: "50년", stats: { speed: 250, critRate: 20, atk: 80 } },
      초절정: { name: "비광검결", innerPower: "120년", stats: { speed: 800, critRate: 35, atk: 300 } },
      화경: { name: "유광절명", innerPower: "200년", stats: { speed: 2500, critRate: 60, atk: 1200 } },
      현경: { name: "광속검", innerPower: "320년", stats: { speed: 10000, critRate: 100, atk: 5000 } },
      생사경: { name: "점창멸살", innerPower: "450년", stats: { speed: 40000, critRate: 200, atk: 20000 } },
      신화경: { name: "광천검", innerPower: "600년", stats: { speed: 150000, critRate: 400, atk: 80000 } },
      천인합일: { name: "광무검신", innerPower: "1000년", stats: { speed: 600000, critRate: 800, atk: 300000 } },
    },
    movement: { entry: "경보", peak: "비광신법", final: "광영무형보" },
  },

  {
    name: "공동파",
    group: "구파일방",
    style: "권법 / 제어",
    summary: "권과 내공의 균형을 중시하는 문파.",
    expBonus: 1,
    coinBonus: 1,
    touchFlavor: "묵직한 권격과 기운이 동시에 밀려옵니다.",
    theme: { glow: "rgba(220,200,255,0.18)", accent: "#e6d8ff" },
    bonusStats: { atk: 20, def: 30, hp: 20 },
    characterImages: { ready: "/images/char_gongdong_ready.png", attack: "/images/char_gongdong_attack.png" },
    specialAdvantage: "공격 시 일정 확률로 적 기절(Stun), 무공 발동 시 적에게 1초간 경직 확정 부여",
    martial: {
      필부: { name: "기초권", innerPower: "-", stats: { atk: 5, def: 5 } },
      삼류: { name: "공동권", innerPower: "2년", stats: { atk: 15, def: 15 } },
      이류: { name: "기공권", innerPower: "8년", stats: { atk: 45, def: 45, hp: 100 } },
      일류: { name: "혼원권", innerPower: "24년", stats: { atk: 150, def: 150, hp: 400 } },
      절정: { name: "공동십이권", innerPower: "50년", stats: { atk: 500, def: 500, hp: 1500 } },
      초절정: { name: "혼원강권", innerPower: "120년", stats: { atk: 2000, def: 2000, hp: 6000 } },
      화경: { name: "공동신공", innerPower: "200년", stats: { atk: 8000, def: 8000, hp: 20000 } },
      현경: { name: "혼원일체", innerPower: "320년", stats: { atk: 30000, def: 30000, hp: 80000 } },
      생사경: { name: "공동멸살", innerPower: "450년", stats: { atk: 120000, def: 120000, hp: 300000 } },
      신화경: { name: "천공권", innerPower: "600년", stats: { atk: 500000, def: 500000, hp: 1200000 } },
      천인합일: { name: "혼원천지", innerPower: "1000년", stats: { atk: 2000000, def: 2000000, hp: 5000000 } },
    },
    movement: { entry: "혼원보", peak: "공동비영보", final: "천공무형보" },
  },

  {
    name: "아미파",
    group: "구파일방",
    style: "유연 / 방어반격",
    summary: "부드러운 흐름으로 방어와 반격을 동시에 수행.",
    expBonus: 1,
    coinBonus: 1,
    touchFlavor: "부드러운 흐름 속에서 타격이 이어집니다.",
    theme: { glow: "rgba(255,180,220,0.18)", accent: "#ffcce6" },
    bonusStats: { eva: 30, hp: 30, def: 20 },
    characterImages: { ready: "/images/char_emei_ready.png", attack: "/images/char_emei_attack.png" },
    specialAdvantage: "피해를 받으면 3초간 회피율 폭증, 방어 성공 후 반격 대미지 강화, 회복 효과 50% 향상",
    martial: {
      필부: { name: "기초장", innerPower: "-", stats: { eva: 3, hp: 40 } },
      삼류: { name: "아미장", innerPower: "2년", stats: { eva: 10, hp: 120 } },
      이류: { name: "유연검", innerPower: "8년", stats: { eva: 20, hp: 400, def: 15 } },
      일류: { name: "아미검법", innerPower: "24년", stats: { eva: 35, hp: 1200, def: 50, atk: 25 } },
      절정: { name: "아미십이식", innerPower: "50년", stats: { eva: 50, hp: 4500, def: 180, atk: 80 } },
      초절정: { name: "유연무극", innerPower: "120년", stats: { eva: 70, hp: 15000, def: 600, atk: 300 } },
      화경: { name: "아미심공", innerPower: "200년", stats: { eva: 100, hp: 45000, def: 2000, atk: 1200 } },
      현경: { name: "무상유연", innerPower: "320년", stats: { eva: 150, hp: 180000, def: 8000, atk: 4500 } },
      생사경: { name: "아미멸혼", innerPower: "450년", stats: { eva: 250, hp: 700000, def: 30000, atk: 15000 } },
      신화경: { name: "선녀강림", innerPower: "600년", stats: { eva: 500, hp: 2500000, def: 120000, atk: 50000 } },
      천인합일: { name: "무극유연체", innerPower: "1000년", stats: { eva: 1000, hp: 12000000, def: 500000, atk: 200000 } },
    },
    movement: { entry: "유연보", peak: "비선신법", final: "무상비영보" },
  },

  {
    name: "곤륜파",
    group: "구파일방",
    style: "빙공 / 제어",
    summary: "차갑게 응축된 기운으로 상대를 얼려버리는 한빙 계열 무학.",
    expBonus: 1,
    coinBonus: 1,
    touchFlavor: "서늘한 한기가 서린 타격이 적을 둔하게 만듭니다.",
    theme: { glow: "rgba(180,230,255,0.22)", accent: "#c2e1ff" },
    bonusStats: { def: 25, atk: 25, speed: 15 },
    characterImages: { ready: "/images/char_kunlun_ready.png", attack: "/images/char_kunlun_attack.png" },
    specialAdvantage: "공격 시 빙결/둔화 스택 누적, 얼어붙은 적에게 추가 피해, 적의 공격속도 영구 감소(전투 중)",
    martial: {
        필부: { name: "기초한빙기", innerPower: "-", stats: { atk: 4, def: 4 } },
        삼류: { name: "한빙권", innerPower: "2년", stats: { atk: 18, def: 18 } },
        이류: { name: "설화장", innerPower: "8년", stats: { atk: 50, def: 50, speed: 5 } },
        일류: { name: "곤륜검법", innerPower: "24년", stats: { atk: 180, def: 180, speed: 12 } },
        절정: { name: "한빙기공", innerPower: "50년", stats: { atk: 600, def: 600, speed: 25 } },
        초절정: { name: "북해빙공", innerPower: "120년", stats: { atk: 2200, def: 2200, speed: 50 } },
        화경: { name: "태을진인", innerPower: "200년", stats: { atk: 9000, def: 9000, speed: 100 } },
        현경: { name: "빙혼일체", innerPower: "320년", stats: { atk: 35000, def: 35000, speed: 250 } },
        생사경: { name: "만년한빙", innerPower: "450년", stats: { atk: 150000, def: 150000, speed: 600 } },
        신화경: { name: "빙제강림", innerPower: "600년", stats: { atk: 600000, def: 600000, speed: 1500 } },
        천인합일: { name: "무극빙천", innerPower: "1000년", stats: { atk: 2500000, def: 2500000, speed: 4000 } },
    },
    movement: { entry: "유운보", peak: "빙표보", final: "천운무형보" },
  },

  // ================= 오대세가 =================

  {
    name: "남궁세가",
    group: "오대세가",
    style: "정통 검기 / 강공",
    summary: "검기와 검강을 극한까지 끌어올리는 검문의 정수.",
    expBonus: 2,
    coinBonus: 0,
    touchFlavor: "절도 있는 검격이 이어집니다.",
    theme: { glow: "rgba(235,245,255,0.2)", accent: "#eef6ff" },
    bonusStats: { atk: 35, critDmg: 40, critRate: 15 },
    characterImages: { ready: "/images/char_namgung_ready.png", attack: "/images/char_namgung_attack.png" },
    specialAdvantage: "무공 발동 시 적의 방어력 100% 무시, 보스 및 엘리트 몬스터 대상 30% 추가 피해",
    martial: {
      필부: { name: "기초검법", innerPower: "-", stats: { atk: 8 } },
      삼류: { name: "남궁검법", innerPower: "2년", stats: { atk: 30, critDmg: 5 } },
      이류: { name: "정검검법", innerPower: "8년", stats: { atk: 100, critDmg: 15 } },
      일류: { name: "천검검법", innerPower: "24년", stats: { atk: 400, critDmg: 40, critRate: 5 } },
      절정: { name: "검기방출", innerPower: "50년", stats: { atk: 1500, critDmg: 100, critRate: 10 } },
      초절정: { name: "검강형성", innerPower: "120년", stats: { atk: 6000, critDmg: 200, critRate: 15 } },
      화경: { name: "검혼일검", innerPower: "200년", stats: { atk: 25000, critDmg: 400, critRate: 20 } },
      현경: { name: "검기귀원공", innerPower: "320년", stats: { atk: 100000, critDmg: 800, critRate: 25 } },
      생사경: { name: "검혼멸살", innerPower: "450년", stats: { atk: 450000, critDmg: 1500, critRate: 35 } },
      신화경: { name: "검왕강림", innerPower: "600년", stats: { atk: 2000000, critDmg: 3000, critRate: 50 } },
      천인합일: { name: "천검천하", innerPower: "1000년", stats: { atk: 10000000, critDmg: 7000, critRate: 80 } },
    },
    movement: { entry: "검영보", peak: "천검비행", final: "무영검신법" },
  },

  {
    name: "제갈세가",
    group: "오대세가",
    style: "전략 / 진법",
    summary: "진법과 계산으로 전장을 지배하는 책략 세가.",
    expBonus: 1,
    coinBonus: 1,
    touchFlavor: "계산된 타격이 이어집니다.",
    theme: { glow: "rgba(200,190,255,0.18)", accent: "#d9d2ff" },
    bonusStats: { speed: 40, critRate: 15, atk: 15 },
    characterImages: { ready: "/images/char_zhuge_ready.png", attack: "/images/char_zhuge_attack.png" },
    specialAdvantage: "일정 주기마다 적 방어/회피/치명율 하락 진법 발동, 전투 시작 시 모든 공격 스탯 5% 버프 획득",
    martial: {
      필부: { name: "기초진보", innerPower: "-", stats: { speed: 4, critRate: 1 } },
      삼류: { name: "기문보법", innerPower: "2년", stats: { speed: 12, critRate: 3 } },
      이류: { name: "팔괘진", innerPower: "8년", stats: { speed: 30, critRate: 6, atk: 10 } },
      일류: { name: "천기검법", innerPower: "24년", stats: { speed: 80, critRate: 10, atk: 40 } },
      절정: { name: "팔진도", innerPower: "50년", stats: { speed: 200, critRate: 15, atk: 150 } },
      초절정: { name: "기문둔갑", innerPower: "120년", stats: { speed: 600, critRate: 25, atk: 500 } },
      화경: { name: "천문진", innerPower: "200년", stats: { speed: 2000, critRate: 40, atk: 1800 } },
      현경: { name: "삼재진", innerPower: "320년", stats: { speed: 8000, critRate: 60, atk: 7000 } },
      생사경: { name: "혼원진", innerPower: "450년", stats: { speed: 32000, critRate: 100, atk: 25000 } },
      신화경: { name: "천문개벽", innerPower: "600년", stats: { speed: 120000, critRate: 200, atk: 100000 } },
      천인합일: { name: "천기천변", innerPower: "1000년", stats: { speed: 500000, critRate: 400, atk: 400000 } },
    },
    movement: { entry: "기문보", peak: "팔괘신법", final: "무형진보" },
  },

  {
    name: "사마세가",
    group: "오대세가",
    style: "내공 지배 / 압도",
    summary: "강대한 내공으로 상대를 압도하는 명문 세가.",
    expBonus: 1,
    coinBonus: 2,
    touchFlavor: "압도적인 내공이 상대를 짓누릅니다.",
    theme: { glow: "rgba(200,200,200,0.18)", accent: "#dddddd" },
    bonusStats: { def: 35, hp: 45, atk: 20 },
    characterImages: { ready: "/images/char_sama_ready.png", attack: "/images/char_sama_attack.png" },
    specialAdvantage: "보유 내공 비례 공격력 상승, 장기전 비례 피해 향상, 일정 대미지 흡수 내공 보호막 생성",
    martial: {
      필부: { name: "기초내공", innerPower: "-", stats: { def: 8, hp: 60 } },
      삼류: { name: "사마내공", innerPower: "2년", stats: { def: 25, hp: 200, atk: 10 } },
      이류: { name: "압기술", innerPower: "8년", stats: { def: 70, hp: 600, atk: 30 } },
      일류: { name: "진기장", innerPower: "24년", stats: { def: 220, hp: 2000, atk: 100 } },
      절정: { name: "사마강기", innerPower: "50년", stats: { def: 750, hp: 7000, atk: 300 } },
      초절정: { name: "내공폭발", innerPower: "120년", stats: { def: 2200, hp: 22000, atk: 1000 } },
      화경: { name: "혼원내공", innerPower: "200년", stats: { def: 9000, hp: 80000, atk: 3500 } },
      현경: { name: "기압지배", innerPower: "320년", stats: { def: 35000, hp: 300000, atk: 12000 } },
      생사경: { name: "사마멸살", innerPower: "450년", stats: { def: 140000, hp: 1200000, atk: 45000 } },
      신화경: { name: "천기지배", innerPower: "600년", stats: { def: 550000, hp: 5000000, atk: 180000 } },
      천인합일: { name: "무형내공체", innerPower: "1000년", stats: { def: 2200000, hp: 20000000, atk: 600000 } },
    },
    movement: { entry: "압기보", peak: "진기비행", final: "무형기보" },
  },

  {
    name: "하북팽가",
    group: "오대세가",
    style: "파괴력 / 일격",
    summary: "묵직한 도로 압도적인 일격을 가하는 세가.",
    expBonus: 2,
    coinBonus: 0,
    touchFlavor: "무거운 도격이 내려꽂힙니다.",
    theme: { glow: "rgba(255,170,120,0.22)", accent: "#ffc39f" },
    bonusStats: { atk: 50, critDmg: 20, critRate: 15 },
    characterImages: { ready: "/images/char_paeng_ready.png", attack: "/images/char_paeng_attack.png" },
    specialAdvantage: "무공 피해 대폭 증가, 적 방어 무시 확률 10%, 치명타 발생 시 적 1초간 확정 경직",
    martial: {
      필부: { name: "기초도법", innerPower: "-", stats: { atk: 12 } },
      삼류: { name: "팽가도법", innerPower: "2년", stats: { atk: 50, critRate: 2 } },
      이류: { name: "광도법", innerPower: "8년", stats: { atk: 180, critRate: 5 } },
      일류: { name: "천강도법", innerPower: "24년", stats: { atk: 800, critRate: 10, critDmg: 20 } },
      절정: { name: "패왕도법", innerPower: "50년", stats: { atk: 3000, critRate: 15, critDmg: 100 } },
      초절정: { name: "도강형성", innerPower: "120년", stats: { atk: 12000, critRate: 20, critDmg: 300 } },
      화경: { name: "천강참", innerPower: "200년", stats: { atk: 55000, critRate: 30, critDmg: 800 } },
      현경: { name: "파천도", innerPower: "320년", stats: { atk: 220000, critRate: 40, critDmg: 2000 } },
      생사경: { name: "단혼멸살", innerPower: "450년", stats: { atk: 1000000, critRate: 55, critDmg: 5000 } },
      신화경: { name: "천뢰멸살", innerPower: "600년", stats: { atk: 5000000, critRate: 80, critDmg: 12000 } },
      천인합일: { name: "패왕강림", innerPower: "1000년", stats: { atk: 25000000, critRate: 120, critDmg: 35000 } },
    },
    movement: { entry: "천강보", peak: "패왕비행", final: "천강신법" },
  },

  {
    name: "사천당가",
    group: "오대세가",
    style: "지속 피해 / 암기",
    summary: "독과 암기로 상대를 서서히 무너뜨리는 세가.",
    expBonus: 1,
    coinBonus: 2,
    touchFlavor: "독이 스며들며 피해가 누적됩니다.",
    theme: { glow: "rgba(120,255,170,0.18)", accent: "#baf7c7" },
    bonusStats: { critRate: 25, eva: 25, atk: 20 },
    characterImages: { ready: "/images/char_dang_ready.png", attack: "/images/char_dang_attack.png" },
    specialAdvantage: "일반 공격 시 5% 확률 랜덤 중독, 독 걸린 적에게 추가 피해, 치명타 시 중독 대미지 2배",
    martial: {
      필부: { name: "암기투척", innerPower: "-", stats: { critRate: 2, atk: 3 } },
      삼류: { name: "독침술", innerPower: "2년", stats: { critRate: 6, atk: 12 } },
      이류: { name: "오독장", innerPower: "8년", stats: { critRate: 12, atk: 40, eva: 5 } },
      일류: { name: "독비도술", innerPower: "24년", stats: { critRate: 20, atk: 140, eva: 12 } },
      절정: { name: "만독장", innerPower: "50년", stats: { critRate: 35, atk: 450, eva: 25 } },
      초절정: { name: "독화만천", innerPower: "120년", stats: { critRate: 55, atk: 1800, eva: 40 } },
      화경: { name: "만독신공", innerPower: "200년", stats: { critRate: 85, atk: 7000, eva: 60 } },
      현경: { name: "독룡내공", innerPower: "320년", stats: { critRate: 140, atk: 28000, eva: 100 } },
      생사경: { name: "만독귀종", innerPower: "450년", stats: { critRate: 280, atk: 110000, eva: 180 } },
      신화경: { name: "천독멸살", innerPower: "600년", stats: { critRate: 600, atk: 450000, eva: 350 } },
      천인합일: { name: "독신강림", innerPower: "1000년", stats: { critRate: 1400, atk: 2000000, eva: 700 } },
    },
    movement: { entry: "독영보", peak: "무영암보", final: "천독비행" },
  },

  {
    name: "일월신교",
    group: "사파",
    style: "흡수 / 음양전환",
    summary: "빨아들이고 뒤집는 음양의 흐름으로 자원을 지배하는 사도 계열.",
    expBonus: 2,
    coinBonus: 1,
    touchFlavor: "허수아비에서 기운을 빨아들이듯 연속으로 타격합니다.",
    theme: { glow: "rgba(180,140,255,0.2)", accent: "#d4c2ff" },
    bonusStats: { atk: 30, hp: 30, def: 30 },
    characterImages: { ready: "/images/char_sunmoon_ready.png", attack: "/images/char_sunmoon_attack.png" },
    specialAdvantage: "가한 피해의 일부를 체력/내공으로 즉시 흡수, 적 방어력 50% 무시, 공격 시 일정확률 체력 회복",
    martial: {
      필부: { name: "기운흡수", innerPower: "-", stats: { atk: 5, hp: 50 } },
      삼류: { name: "흡기공", innerPower: "2년", stats: { atk: 20, hp: 200 } },
      이류: { name: "혈월장", innerPower: "8년", stats: { atk: 60, hp: 500, def: 20 } },
      일류: { name: "일월검법", innerPower: "24년", stats: { atk: 220, hp: 1800, def: 60 } },
      절정: { name: "흡성대법", innerPower: "50년", stats: { atk: 800, hp: 6000, def: 250, critRate: 8 } },
      초절정: { name: "원기흡수", innerPower: "120년", stats: { atk: 3000, hp: 20000, def: 800, critRate: 15 } },
      화경: { name: "음양합일공", innerPower: "200년", stats: { atk: 12000, hp: 70000, def: 3000, critRate: 25 } },
      현경: { name: "일월합일", innerPower: "320년", stats: { atk: 50000, hp: 250000, def: 12000, critRate: 35 } },
      생사경: { name: "흡성멸살", innerPower: "450년", stats: { atk: 220000, hp: 1000000, def: 50000, critRate: 50 } },
      신화경: { name: "일월천하", innerPower: "600년", stats: { atk: 1000000, hp: 4000000, def: 200000, critRate: 80 } },
      천인합일: { name: "일월귀일", innerPower: "1000년", stats: { atk: 5000000, hp: 15000000, def: 800000, critRate: 150 } },
    },
    movement: { entry: "월영보", peak: "일월유광보", final: "일월무형보" },
  },

  {
    name: "천마신교",
    group: "마교",
    style: "광폭 / 폭딜",
    summary: "마기를 폭주시키며 압도적 화력으로 밀어붙이는 최종 보스급 무학.",
    expBonus: 3,
    coinBonus: 0,
    touchFlavor: "마기가 폭주하듯 거칠고 강한 일격이 연속으로 꽂힙니다.",
    theme: { glow: "rgba(255,80,120,0.22)", accent: "#ffafc4" },
    bonusStats: { atk: 60, critDmg: 60, critRate: 20 },
    characterImages: { ready: "/images/char_heavenly_ready.png", attack: "/images/char_heavenly_attack.png" },
    specialAdvantage: "체력이 낮을수록 공격력 폭발적 증가, 일정 시간 광폭화 발동, 무공 발동 시 피해 5배 및 5초간 치명타율 +20%",
    martial: {
      필부: { name: "마기응축", innerPower: "-", stats: { atk: 15 } },
      삼류: { name: "마기장", innerPower: "2년", stats: { atk: 60, critDmg: 10 } },
      이류: { name: "혈마검법", innerPower: "8년", stats: { atk: 250, critDmg: 25 } },
      일류: { name: "천마검법", innerPower: "24년", stats: { atk: 1000, critDmg: 60, critRate: 10 } },
      절정: { name: "마기폭주", innerPower: "50년", stats: { atk: 4500, critDmg: 150, critRate: 15 } },
      초절정: { name: "혈기폭발", innerPower: "120년", stats: { atk: 20000, critDmg: 400, critRate: 25 } },
      화경: { name: "천마신공", innerPower: "200년", stats: { atk: 100000, critDmg: 1000, critRate: 35 } },
      현경: { name: "마혼지배", innerPower: "320년", stats: { atk: 500000, critDmg: 3000, critRate: 50 } },
      생사경: { name: "혈마멸살", innerPower: "450년", stats: { atk: 2500000, critDmg: 8000, critRate: 80 } },
      신화경: { name: "천마천하", innerPower: "600년", stats: { atk: 12000000, critDmg: 20000, critRate: 120 } },
      천인합일: { name: "천마불멸", innerPower: "1000년", stats: { atk: 80000000, critDmg: 60000, critRate: 200 } },
    },
    movement: { entry: "혈영보", peak: "천마비영신법", final: "천마무극보" },
  },

];