import type { OwnedWeapon } from "./types";

export type SetOption = {
  requiredPieces: number;
  attackBonusMultiplier?: number;
  critRateBonus?: number;
  description: string;
};

export const REALM_SET_OPTIONS: Record<string, SetOption> = {
  "절정": { requiredPieces: 5, attackBonusMultiplier: 1.2, critRateBonus: 5, description: "절정 세트: 총 공격력 20% 증폭, 치명타율 5% 증가" },
  "초절정": { requiredPieces: 5, attackBonusMultiplier: 1.35, critRateBonus: 8, description: "초절정 세트: 총 공격력 35% 증폭, 치명타율 8% 증가" },
  "화경": { requiredPieces: 5, attackBonusMultiplier: 1.5, critRateBonus: 12, description: "화경 세트: 총 공격력 50% 증폭, 치명타율 12% 증가" },
  "현경": { requiredPieces: 5, attackBonusMultiplier: 1.8, critRateBonus: 15, description: "현경 세트: 총 공격력 80% 증폭, 치명타율 15% 증가" },
  "생사경": { requiredPieces: 5, attackBonusMultiplier: 2.2, critRateBonus: 20, description: "생사경 세트: 총 공격력 120% 증폭, 치명타율 20% 증가" },
  "신화경": { requiredPieces: 5, attackBonusMultiplier: 3, critRateBonus: 25, description: "신화경 세트: 총 공격력 200% 증폭, 치명타율 25% 증가" },
  "천인합일": { requiredPieces: 5, attackBonusMultiplier: 5, critRateBonus: 35, description: "천인합일 세트: 총 공격력 400% 증폭, 치명타율 35% 증가" },
};

export const FORGE_ITEMS: OwnedWeapon[] = [
  {
    id: "필부_mainWeapon",
    name: "무명철검",
    slot: "mainWeapon",
    realm: "필부",
    attackBonus: 10,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    touchMultiplier: 100,
    price: 1000,
    icon: "⚔️",
    description: "공격 +10 | 수련 +100",
  },
  {
    id: "필부_subWeapon",
    name: "무명단검",
    slot: "subWeapon",
    realm: "필부",
    attackBonus: 6,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 600,
    icon: "🗡️",
    description: "공격 +6",
  },
  {
    id: "필부_gloves",
    name: "거친 가죽장갑",
    slot: "gloves",
    realm: "필부",
    attackBonus: 2,
    critBonus: 1,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 600,
    icon: "🧤",
    description: "공격 +2 | 치명타 +1%",
  },
  {
    id: "필부_shoes",
    name: "거친 짚신",
    slot: "shoes",
    realm: "필부",
    attackBonus: 2,
    critBonus: 0,
    evadeBonus: 1,
    defenseBonus: 0,
    price: 600,
    icon: "👢",
    description: "공격 +2 | 회피 +1%",
  },
  {
    id: "필부_robe",
    name: "무명 도포",
    slot: "robe",
    realm: "필부",
    attackBonus: 2,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 5,
    price: 600,
    icon: "🥋",
    description: "공격 +2 | 방어 +5",
  },
  {
    id: "삼류_mainWeapon",
    name: "강철장검",
    slot: "mainWeapon",
    realm: "삼류",
    attackBonus: 30,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 5000,
    icon: "⚔️",
    description: "공격 +30",
  },
  {
    id: "삼류_subWeapon",
    name: "강철비수",
    slot: "subWeapon",
    realm: "삼류",
    attackBonus: 18,
    critBonus: 1,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 3000,
    icon: "🗡️",
    description: "공격 +18 | 치명타 +1%",
  },
  {
    id: "삼류_gloves",
    name: "질긴 가죽장갑",
    slot: "gloves",
    realm: "삼류",
    attackBonus: 6,
    critBonus: 2,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 3000,
    icon: "🧤",
    description: "공격 +6 | 치명타 +2%",
  },
  {
    id: "삼류_shoes",
    name: "단단한 가죽신",
    slot: "shoes",
    realm: "삼류",
    attackBonus: 6,
    critBonus: 0,
    evadeBonus: 2,
    defenseBonus: 0,
    price: 3000,
    icon: "👢",
    description: "공격 +6 | 회피 +2%",
  },
  {
    id: "삼류_robe",
    name: "견고한 무복",
    slot: "robe",
    realm: "삼류",
    attackBonus: 6,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 10,
    price: 3000,
    icon: "🥋",
    description: "공격 +6 | 방어 +10",
  },
  {
    id: "이류_mainWeapon",
    name: "백련검",
    slot: "mainWeapon",
    realm: "이류",
    attackBonus: 80,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 25000,
    icon: "⚔️",
    description: "공격 +80",
  },
  {
    id: "이류_subWeapon",
    name: "백련비수",
    slot: "subWeapon",
    realm: "이류",
    attackBonus: 48,
    critBonus: 2,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 15000,
    icon: "🗡️",
    description: "공격 +48 | 치명타 +2%",
  },
  {
    id: "이류_gloves",
    name: "백련 철장갑",
    slot: "gloves",
    realm: "이류",
    attackBonus: 16,
    critBonus: 4,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 15000,
    icon: "🧤",
    description: "공격 +16 | 치명타 +4%",
  },
  {
    id: "이류_shoes",
    name: "경량 철화",
    slot: "shoes",
    realm: "이류",
    attackBonus: 16,
    critBonus: 0,
    evadeBonus: 3,
    defenseBonus: 0,
    price: 15000,
    icon: "👢",
    description: "공격 +16 | 회피 +3%",
  },
  {
    id: "이류_robe",
    name: "은사 도포",
    slot: "robe",
    realm: "이류",
    attackBonus: 16,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 20,
    price: 15000,
    icon: "🥋",
    description: "공격 +16 | 방어 +20",
  },
  {
    id: "일류_mainWeapon",
    name: "청강검",
    slot: "mainWeapon",
    realm: "일류",
    attackBonus: 250,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 100000,
    icon: "⚔️",
    description: "공격 +250",
  },
  {
    id: "일류_subWeapon",
    name: "청강접도",
    slot: "subWeapon",
    realm: "일류",
    attackBonus: 150,
    critBonus: 3,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 60000,
    icon: "🗡️",
    description: "공격 +150 | 치명타 +3%",
  },
  {
    id: "일류_gloves",
    name: "운모 장갑",
    slot: "gloves",
    realm: "일류",
    attackBonus: 50,
    critBonus: 6,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 60000,
    icon: "🧤",
    description: "공격 +50 | 치명타 +6%",
  },
  {
    id: "일류_shoes",
    name: "비연신",
    slot: "shoes",
    realm: "일류",
    attackBonus: 50,
    critBonus: 0,
    evadeBonus: 5,
    defenseBonus: 0,
    price: 60000,
    icon: "👢",
    description: "공격 +50 | 회피 +5%",
  },
  {
    id: "일류_robe",
    name: "청사 무복",
    slot: "robe",
    realm: "일류",
    attackBonus: 50,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 50,
    price: 60000,
    icon: "🥋",
    description: "공격 +50 | 방어 +50",
  },
  {
    id: "절정_mainWeapon",
    name: "벽력신검",
    slot: "mainWeapon",
    realm: "절정",
    attackBonus: 800,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 500000,
    icon: "⚔️",
    description: "공격 +800",
  },
  {
    id: "절정_subWeapon",
    name: "벽력소도",
    slot: "subWeapon",
    realm: "절정",
    attackBonus: 480,
    critBonus: 4,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 300000,
    icon: "🗡️",
    description: "공격 +480 | 치명타 +4%",
  },
  {
    id: "절정_gloves",
    name: "벽력투갑",
    slot: "gloves",
    realm: "절정",
    attackBonus: 160,
    critBonus: 8,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 300000,
    icon: "🧤",
    description: "공격 +160 | 치명타 +8%",
  },
  {
    id: "절정_shoes",
    name: "벽력화",
    slot: "shoes",
    realm: "절정",
    attackBonus: 160,
    critBonus: 0,
    evadeBonus: 8,
    defenseBonus: 0,
    price: 300000,
    icon: "👢",
    description: "공격 +160 | 회피 +8%",
  },
  {
    id: "절정_robe",
    name: "벽력금의",
    slot: "robe",
    realm: "절정",
    attackBonus: 160,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 120,
    price: 300000,
    icon: "🥋",
    description: "공격 +160 | 방어 +120",
  },
  {
    id: "초절정_mainWeapon",
    name: "용연검",
    slot: "mainWeapon",
    realm: "초절정",
    attackBonus: 2500,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 2000000,
    icon: "⚔️",
    description: "공격 +2,500",
    equipmentSkill: { name: "초절정의 격돌", multiplier: 15 },
    
  },
  {
    id: "초절정_subWeapon",
    name: "용린비수",
    slot: "subWeapon",
    realm: "초절정",
    attackBonus: 1500,
    critBonus: 5,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 1200000,
    icon: "🗡️",
    description: "공격 +1,500 | 치명타 +5%",
    equipmentSkill: { name: "초절정의 격돌", multiplier: 12 },
    
  },
  {
    id: "초절정_gloves",
    name: "용린장갑",
    slot: "gloves",
    realm: "초절정",
    attackBonus: 500,
    critBonus: 10,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 1200000,
    icon: "🧤",
    description: "공격 +500 | 치명타 +10%",
  },
  {
    id: "초절정_shoes",
    name: "용린보",
    slot: "shoes",
    realm: "초절정",
    attackBonus: 500,
    critBonus: 0,
    evadeBonus: 12,
    defenseBonus: 0,
    price: 1200000,
    icon: "👢",
    description: "공격 +500 | 회피 +12%",
  },
  {
    id: "초절정_robe",
    name: "용린갑",
    slot: "robe",
    realm: "초절정",
    attackBonus: 500,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 300,
    price: 1200000,
    icon: "🥋",
    description: "공격 +500 | 방어 +300",
  },
  {
    id: "화경_mainWeapon",
    name: "태허무극검",
    slot: "mainWeapon",
    realm: "화경",
    attackBonus: 8000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 10000000,
    icon: "⚔️",
    description: "공격 +8,000",
    equipmentSkill: { name: "화경의 격돌", multiplier: 17 },
    
  },
  {
    id: "화경_subWeapon",
    name: "태허단검",
    slot: "subWeapon",
    realm: "화경",
    attackBonus: 4800,
    critBonus: 6,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 6000000,
    icon: "🗡️",
    description: "공격 +4,800 | 치명타 +6%",
    equipmentSkill: { name: "화경의 격돌", multiplier: 14 },
    
  },
  {
    id: "화경_gloves",
    name: "태허권갑",
    slot: "gloves",
    realm: "화경",
    attackBonus: 1600,
    critBonus: 12,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 6000000,
    icon: "🧤",
    description: "공격 +1,600 | 치명타 +12%",
  },
  {
    id: "화경_shoes",
    name: "태허비보",
    slot: "shoes",
    realm: "화경",
    attackBonus: 1600,
    critBonus: 0,
    evadeBonus: 15,
    defenseBonus: 0,
    price: 6000000,
    icon: "👢",
    description: "공격 +1,600 | 회피 +15%",
  },
  {
    id: "화경_robe",
    name: "태허도의",
    slot: "robe",
    realm: "화경",
    attackBonus: 1600,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 800,
    price: 6000000,
    icon: "🥋",
    description: "공격 +1,600 | 방어 +800",
  },
  {
    id: "현경_mainWeapon",
    name: "천뢰격진검",
    slot: "mainWeapon",
    realm: "현경",
    attackBonus: 25000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 50000000,
    icon: "⚔️",
    description: "공격 +25,000",
    equipmentSkill: { name: "현경의 격돌", multiplier: 19 },
    
  },
  {
    id: "현경_subWeapon",
    name: "천뢰소수",
    slot: "subWeapon",
    realm: "현경",
    attackBonus: 15000,
    critBonus: 7,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 30000000,
    icon: "🗡️",
    description: "공격 +15,000 | 치명타 +7%",
    equipmentSkill: { name: "현경의 격돌", multiplier: 16 },
    
  },
  {
    id: "현경_gloves",
    name: "천뢰강갑",
    slot: "gloves",
    realm: "현경",
    attackBonus: 5000,
    critBonus: 15,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 30000000,
    icon: "🧤",
    description: "공격 +5,000 | 치명타 +15%",
  },
  {
    id: "현경_shoes",
    name: "천뢰비행신",
    slot: "shoes",
    realm: "현경",
    attackBonus: 5000,
    critBonus: 0,
    evadeBonus: 20,
    defenseBonus: 0,
    price: 30000000,
    icon: "👢",
    description: "공격 +5,000 | 회피 +20%",
  },
  {
    id: "현경_robe",
    name: "천뢰마의",
    slot: "robe",
    realm: "현경",
    attackBonus: 5000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 2000,
    price: 30000000,
    icon: "🥋",
    description: "공격 +5,000 | 방어 +2000",
  },
  {
    id: "생사경_mainWeapon",
    name: "단혼멸살검",
    slot: "mainWeapon",
    realm: "생사경",
    attackBonus: 80000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 250000000,
    icon: "⚔️",
    description: "공격 +80,000",
    equipmentSkill: { name: "생사경의 격돌", multiplier: 21 },
    
  },
  {
    id: "생사경_subWeapon",
    name: "단혼절명기",
    slot: "subWeapon",
    realm: "생사경",
    attackBonus: 48000,
    critBonus: 10,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 150000000,
    icon: "🗡️",
    description: "공격 +48,000 | 치명타 +10%",
    equipmentSkill: { name: "생사경의 격돌", multiplier: 18 },
    
  },
  {
    id: "생사경_gloves",
    name: "단혼파멸갑",
    slot: "gloves",
    realm: "생사경",
    attackBonus: 16000,
    critBonus: 20,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 150000000,
    icon: "🧤",
    description: "공격 +16,000 | 치명타 +20%",
  },
  {
    id: "생사경_shoes",
    name: "단혼유영보",
    slot: "shoes",
    realm: "생사경",
    attackBonus: 16000,
    critBonus: 0,
    evadeBonus: 25,
    defenseBonus: 0,
    price: 150000000,
    icon: "👢",
    description: "공격 +16,000 | 회피 +25%",
  },
  {
    id: "생사경_robe",
    name: "단혼장속",
    slot: "robe",
    realm: "생사경",
    attackBonus: 16000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 5000,
    price: 150000000,
    icon: "🥋",
    description: "공격 +16,000 | 방어 +5000",
  },
  {
    id: "신화경_mainWeapon",
    name: "신성천우검",
    slot: "mainWeapon",
    realm: "신화경",
    attackBonus: 300000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 1000000000,
    icon: "⚔️",
    description: "공격 +300,000",
    equipmentSkill: { name: "신화경의 격돌", multiplier: 23 },
    
  },
  {
    id: "신화경_subWeapon",
    name: "신성월광기",
    slot: "subWeapon",
    realm: "신화경",
    attackBonus: 180000,
    critBonus: 12,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 600000000,
    icon: "🗡️",
    description: "공격 +180,000 | 치명타 +12%",
    equipmentSkill: { name: "신화경의 격돌", multiplier: 20 },
    
  },
  {
    id: "신화경_gloves",
    name: "신성수호갑",
    slot: "gloves",
    realm: "신화경",
    attackBonus: 60000,
    critBonus: 25,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 600000000,
    icon: "🧤",
    description: "공격 +60,000 | 치명타 +25%",
  },
  {
    id: "신화경_shoes",
    name: "신성창공보",
    slot: "shoes",
    realm: "신화경",
    attackBonus: 60000,
    critBonus: 0,
    evadeBonus: 30,
    defenseBonus: 0,
    price: 600000000,
    icon: "👢",
    description: "공격 +60,000 | 회피 +30%",
  },
  {
    id: "신화경_robe",
    name: "신성천상의",
    slot: "robe",
    realm: "신화경",
    attackBonus: 60000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 12000,
    price: 600000000,
    icon: "🥋",
    description: "공격 +60,000 | 방어 +12000",
  },
  {
    id: "천인합일_mainWeapon",
    name: "천지개벽검",
    slot: "mainWeapon",
    realm: "천인합일",
    attackBonus: 1000000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 5000000000,
    icon: "⚔️",
    description: "공격 +1,000,000",
    equipmentSkill: { name: "천인합일의 격돌", multiplier: 25 },
    
  },
  {
    id: "천인합일_subWeapon",
    name: "천무멸각기",
    slot: "subWeapon",
    realm: "천인합일",
    attackBonus: 600000,
    critBonus: 17,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 3000000000,
    icon: "🗡️",
    description: "공격 +600,000 | 치명타 +17%",
    equipmentSkill: { name: "천인합일의 격돌", multiplier: 22 },
    
  },
  {
    id: "천인합일_gloves",
    name: "천지합일갑",
    slot: "gloves",
    realm: "천인합일",
    attackBonus: 200000,
    critBonus: 35,
    evadeBonus: 0,
    defenseBonus: 0,
    price: 3000000000,
    icon: "🧤",
    description: "공격 +200,000 | 치명타 +35%",
  },
  {
    id: "천인합일_shoes",
    name: "천인보무",
    slot: "shoes",
    realm: "천인합일",
    attackBonus: 200000,
    critBonus: 0,
    evadeBonus: 40,
    defenseBonus: 0,
    price: 3000000000,
    icon: "👢",
    description: "공격 +200,000 | 회피 +40%",
  },
  {
    id: "천인합일_robe",
    name: "천하무적갑",
    slot: "robe",
    realm: "천인합일",
    attackBonus: 200000,
    critBonus: 0,
    evadeBonus: 0,
    defenseBonus: 30000,
    price: 3000000000,
    icon: "🥋",
    description: "공격 +200,000 | 방어 +30000",
  },
];

export const STARTER_EQUIPMENT: OwnedWeapon[] = [
  FORGE_ITEMS.find(i => i.id === "필부_mainWeapon")!,
  FORGE_ITEMS.find(i => i.id === "필부_subWeapon")!,
  FORGE_ITEMS.find(i => i.id === "필부_gloves")!,
  FORGE_ITEMS.find(i => i.id === "필부_shoes")!,
  FORGE_ITEMS.find(i => i.id === "필부_robe")!,
];

export const MASTER_RIVALS = [
  { name: "창랑검객", hpMult: 1.2, atkMult: 1.1 },
  { name: "혈랑도수", hpMult: 1.5, atkMult: 1.3 },
  { name: "청운도인", hpMult: 2.0, atkMult: 1.6 },
  { name: "백발마녀", hpMult: 3.0, atkMult: 2.2 },
  { name: "귀영살수", hpMult: 5.0, atkMult: 4.0 },
  { name: "북해빙궁주", hpMult: 10.0, atkMult: 8.0 },
  { name: "남만중독왕", hpMult: 25.0, atkMult: 18.0 },
  { name: "철혈무정객", hpMult: 60.0, atkMult: 45.0 },
  { name: "천마외도", hpMult: 150.0, atkMult: 120.0 },
  { name: "검신", hpMult: 500.0, atkMult: 400.0 },
];

export const RANDOM_OPTION_POOL = [
  { stat: "atk_pct", label: "공격력", suffix: "%", range: [5, 15] },
  { stat: "crit_rate", label: "치명타율", suffix: "%", range: [3, 8] },
  { stat: "crit_dmg", label: "치명타 피해", suffix: "%", range: [15, 40] },
  { stat: "eva", label: "회피율", suffix: "%", range: [3, 10] },
  { stat: "hp_pct", label: "생명력", suffix: "%", range: [10, 25] },
  { stat: "mp_pct", label: "내공", suffix: "%", range: [10, 25] },
  { stat: "exp_pct", label: "수련 효율", suffix: "%", range: [20, 50] },
];

export const SYNERGY_SETS: Record<string, { label: string, description: string }> = {
  "파천": { label: "파천 (공격)", description: "3세트: 공격력 25% 증폭 | 5세트: 최종 대미지 20% 추가" },
  "멸절": { label: "멸절 (치명피해)", description: "3세트: 치명타 피해 60% 증가 | 5세트: 치명타 시 10% 확률로 대미지 2배" },
  "빙화": { label: "빙화 (치명)", description: "3세트: 치명타율 20% 증가 | 5세트: 공격 시 내공 2% 회복" },
  "태극": { label: "태극 (균형)", description: "3세트: 공격력 15%, 치명타율 7% 증가 | 5세트: 모든 속성 10% 강화" },
};

export function rollTierAndOptions(item: any, level: number, luck: number = 0) {
  const luckBonus = luck * 0.2; // 기연 1포인트당 가중치 0.2% 증가
  const rand = Math.random() * 100;
  let tier: ItemTier = "평범";
  let optionCount = 0;

  if (rand < (5 + luckBonus)) { tier = "신기"; optionCount = 3; }
  else if (rand < (20 + luckBonus * 2)) { tier = "보구"; optionCount = 2; }
  else if (rand < (50 + luckBonus * 4)) { tier = "명품"; optionCount = 1; }

  const options: RandomOption[] = [];
  const pool = [...RANDOM_OPTION_POOL];
  for (let i = 0; i < optionCount; i++) {
    if (pool.length === 0) break;
    const idx = Math.floor(Math.random() * pool.length);
    const opt = pool.splice(idx, 1)[0];
    
    // 기연이 높을수록 랜덤 옵션 수치도 소폭 높게 나올 확률
    const minVal = opt.range[0];
    const maxVal = opt.range[1];
    const luckRoll = Math.min(luck * 0.1, (maxVal - minVal) * 0.5);
    const value = Math.floor(minVal + luckRoll + Math.random() * (maxVal - minVal + 1 - luckRoll));
    
    options.push({ stat: opt.stat, value, label: `${opt.label} +${value}${opt.suffix}` });
  }

  // 시너지 세트 부여 (명품 이상부터 40% 확률 + 기연 보조)
  let setName = undefined;
  if (tier !== "평범" && Math.random() < (0.4 + luck * 0.01)) {
    const setKeys = Object.keys(SYNERGY_SETS);
    setName = setKeys[Math.floor(Math.random() * setKeys.length)];
  }

  return { ...item, tier, randomOptions: options, setName };
}

export function generateRandomAccessory(realm: string, level: number, luck: number = 0): OwnedWeapon {
  const isNecklace = Math.random() < 0.5;
  const id = `${realm}_${isNecklace ? "necklace" : "ring"}_${Date.now()}`;
  
  const baseName = isNecklace ? "목걸이" : "반지";
  const realms = ["필부", "삼류", "이류", "일류", "절정", "초절정", "화경", "현경", "생사경", "신화경", "천인합일"];
  const rIdx = realms.indexOf(realm);
  const baseForgePrice = [1000, 5000, 25000, 100000, 500000, 2000000, 10000000, 50000000, 250000000, 1000000000, 5000000000][rIdx] || 1000;
  const calculatedPrice = Math.floor(baseForgePrice * (1 + level * 0.1) * 1.2);

  const baseItem: any = {
    id,
    name: `${realm}의 ${baseName}`,
    slot: isNecklace ? "necklace" : "ring",
    realm: realm as any,
    attackBonus: 10 + level * 20,
    mpBonus: 20 + level * 30,
    price: calculatedPrice,
    icon: isNecklace ? "📿" : "💍",
    description: `대결을 통해 획득한 전리품입니다.`,
  };

  const tieredItem = rollTierAndOptions(baseItem, level, luck);
  
  // 신기 등급에는 특수 효과(스킬) 부여 확률
  if (tieredItem.tier === "신기" && Math.random() < (0.5 + luck * 0.02)) {
     tieredItem.equipmentSkill = { name: "전설의 광휘", multiplier: 20 };
  }

  return tieredItem as OwnedWeapon;
}
