import {
  SynthesisRecipe,
  getSkillByFactionAndName,
} from "./martialArtsSystem";

function req(factionName: string, skillName: string) {
  const skill = getSkillByFactionAndName(factionName, skillName);
  if (!skill) {
    // 런타임 오류 방지를 위해 더미 ID 반환 및 콘솔 경고
    console.warn(`[합일 레시피 오류] ${factionName} - ${skillName} 무공을 찾을 수 없습니다.`);
    return `${factionName}__missing__${skillName}`;
  }
  return skill.id;
}

export const MARTIAL_SYNTHESIS_RECIPES: SynthesisRecipe[] = [
  {
    id: "hwasan_plum_blossom_unity",
    factionName: "화산파",
    resultName: "십이매화유영검",
    resultDescription: "매화의 검의와 유영보가 합쳐진 화산의 합일 비기. 화면 전체를 뒤덮는 매화검기를 발동합니다.",
    resultCategory: "sword",
    resultElement: "fire",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("화산파", "매화십이검"),
      req("화산파", "홍화비연보"),
    ],
    requiredStars: 7,
    wisdomCost: 400,
    goldCost: 5000,
  },
  {
    id: "shaolin_vajra_arhat_unity",
    factionName: "소림",
    resultName: "나한금강보살권",
    resultDescription: "금강의 강체와 나한의 권세를 합친 소림 비전. 절대적인 방어력과 파괴력을 동시에 가집니다.",
    resultCategory: "fist",
    resultElement: "yang",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("소림", "나한십팔수"),
      req("소림", "금강비천보"),
    ],
    requiredStars: 7,
    wisdomCost: 420,
    goldCost: 5200,
  },
  {
    id: "wudang_taiji_formless",
    factionName: "무당",
    resultName: "태극무형검세",
    resultDescription: "태극의 흐름과 무형의 신법이 하나가 된 검세. 적의 공격을 무력화하며 반격합니다.",
    resultCategory: "sword",
    resultElement: "yin",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("무당", "태극십삼세"),
      req("무당", "태극유운보"),
    ],
    requiredStars: 7,
    wisdomCost: 430,
    goldCost: 5400,
  },
  {
    id: "gaebang_dragon_beggar_unity",
    factionName: "개방",
    resultName: "강룡걸왕무",
    resultDescription: "항룡의 패도와 걸인의 자유로운 보법이 결합된 실전 절기. 비정형적인 궤적으로 적을 타격합니다.",
    resultCategory: "palm",
    resultElement: "wind",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("개방", "강룡십팔장"),
      req("개방", "걸인신법"),
    ],
    requiredStars: 7,
    wisdomCost: 430,
    goldCost: 5400,
  },
  {
    id: "cheongseong_shadow_kill",
    factionName: "청성파",
    resultName: "청풍무영절명검",
    resultDescription: "속검과 무형보가 극한으로 결합된 암살 비검. 보이지 않는 속도로 급소를 찌릅니다.",
    resultCategory: "sword",
    resultElement: "wind",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("청성파", "비영절명검"),
      req("청성파", "비영신법"),
    ],
    requiredStars: 7,
    wisdomCost: 450,
    goldCost: 5600,
  },
  {
    id: "jeomchang_speed_flash",
    factionName: "점창파",
    resultName: "광영절공연환검",
    resultDescription: "광속 연환검과 광영 무형보의 완성형. 연속적인 타격이 하나의 빛줄기가 됩니다.",
    resultCategory: "sword",
    resultElement: "lightning",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("점창파", "비광검결"),
      req("점창파", "비광신법"),
    ],
    requiredStars: 7,
    wisdomCost: 450,
    goldCost: 5600,
  },
  {
    id: "gongdong_honwon_control",
    factionName: "공동파",
    resultName: "혼원쇄신권",
    resultDescription: "혼원의 기공과 보법이 결합되어 적을 봉쇄하는 제압 무공. 적의 기혈을 막아 마비시킵니다.",
    resultCategory: "fist",
    resultElement: "yang",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("공동파", "혼원강권"),
      req("공동파", "공동비영보"),
    ],
    requiredStars: 7,
    wisdomCost: 420,
    goldCost: 5200,
  },
  {
    id: "emei_grace_counter",
    factionName: "아미파",
    resultName: "비선유영반화결",
    resultDescription: "유연한 반격의 흐름을 극대화한 아미 합일 절기. 꽃잎이 흩날리듯 부드럽지만 치명적입니다.",
    resultCategory: "hybrid",
    resultElement: "water",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("아미파", "유연무극"),
      req("아미파", "비선신법"),
    ],
    requiredStars: 7,
    wisdomCost: 430,
    goldCost: 5300,
  },
  {
    id: "kunlun_ice_soul",
    factionName: "곤륜파",
    resultName: "빙혼천운극",
    resultDescription: "한빙의 기운과 천운 무형보가 융합된 곤륜의 극한 비기. 주변의 모든 것을 빙결시킵니다.",
    resultCategory: "internal",
    resultElement: "ice",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("곤륜파", "북해빙공"),
      req("곤륜파", "빙표보"),
    ],
    requiredStars: 7,
    wisdomCost: 450,
    goldCost: 5600,
  },
  {
    id: "namgung_heaven_sword",
    factionName: "남궁세가",
    resultName: "천검강섬",
    resultDescription: "검강과 비행보가 일체가 된 남궁의 고속 참격 비기. 정통 검문의 위엄을 보여줍니다.",
    resultCategory: "sword",
    resultElement: "lightning",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("남궁세가", "검강형성"),
      req("남궁세가", "천검비행"),
    ],
    requiredStars: 8,
    wisdomCost: 500,
    goldCost: 6500,
  },
  {
    id: "jegal_heaven_formation",
    factionName: "제갈세가",
    resultName: "천기무형진",
    resultDescription: "팔진도와 무형진보를 결합한 제갈세가 최고 진식. 전장을 완벽하게 통제합니다.",
    resultCategory: "formation",
    resultElement: "neutral",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("제갈세가", "팔진도"),
      req("제갈세가", "무형진보"),
    ],
    requiredStars: 8,
    wisdomCost: 500,
    goldCost: 6500,
  },
  {
    id: "sama_inner_dominion",
    factionName: "사마세가",
    resultName: "무형진천강기",
    resultDescription: "내공과 압기의 극한 경지에서 발현되는 강기 지배술. 보이지 않는 기운으로 적을 압살합니다.",
    resultCategory: "internal",
    resultElement: "yang",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("사마세가", "혼원내공"),
      req("사마세가", "진기비행"),
    ],
    requiredStars: 8,
    wisdomCost: 510,
    goldCost: 6700,
  },
  {
    id: "paeng_dominator_blade",
    factionName: "하북팽가",
    resultName: "패왕천강멸도",
    resultDescription: "패왕도와 천강신법이 하나가 된 극일격 도법. 단 한 번의 휘두름으로 산을 가릅니다.",
    resultCategory: "blade",
    resultElement: "lightning",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("하북팽가", "패왕도법"),
      req("하북팽가", "패왕비행"),
    ],
    requiredStars: 8,
    wisdomCost: 530,
    goldCost: 7000,
  },
  {
    id: "dang_poison_shadow",
    factionName: "사천당가",
    resultName: "천독무형살",
    resultDescription: "독과 암기의 정수를 무형보에 얹은 살초. 소리도 흔적도 없이 적을 절명케 합니다.",
    resultCategory: "throwing",
    resultElement: "poison",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("사천당가", "독화만천"),
      req("사천당가", "무영암보"),
    ],
    requiredStars: 8,
    wisdomCost: 530,
    goldCost: 7000,
  },
  {
    id: "sunmoon_yinyang_devour",
    factionName: "일월신교",
    resultName: "일월흡성환류",
    resultDescription: "흡성대법과 일월유광보가 완성한 자원 역류 비기. 적의 기운을 자신의 것으로 치환합니다.",
    resultCategory: "internal",
    resultElement: "yin",
    resultGrade: "legendary",
    requiredSkillIds: [
      req("일월신교", "흡성대법"),
      req("일월신교", "일월유광보"),
    ],
    requiredStars: 8,
    wisdomCost: 550,
    goldCost: 7200,
  },
  {
    id: "cheonma_berserk_apex",
    factionName: "천마신교",
    resultName: "천마혈섬무극",
    resultDescription: "광폭화와 무극보가 융합된 최종 폭멸 비기. 마교의 패도를 천하에 떨칩니다.",
    resultCategory: "blade",
    resultElement: "fire",
    resultGrade: "mythic",
    requiredSkillIds: [
      req("천마신교", "천마신공"),
      req("천마신교", "천마비영신법"),
    ],
    requiredStars: 10,
    wisdomCost: 1000,
    goldCost: 15000,
  },
];
