import type { NextConfig } from "next";

const excludes = [
  './public/**/*',
  'public/**/*',
  './public/thumbnails/**/*',
  'public/thumbnails/**/*',
  './public/images/**/*',
  'public/images/**/*',
  './public/warrior/**/*',
  'public/warrior/**/*',
  './ffmpeg.exe',
  'ffmpeg.exe',
  './scripts/ffmpeg.exe',
  'scripts/ffmpeg.exe',
  '**/ffmpeg.exe',
  './**/*.exe',
  '**/*.exe',
  './*.exe',
  '*.exe',
  './**/*.py',
  '**/*.py',
  './*.py',
  '*.py',
  './**/*.mp3',
  '**/*.mp3',
  './*.mp3',
  '*.mp3',
  './**/*.zip',
  '**/*.zip',
  './*.zip',
  '*.zip',
  './**/*.patch',
  '**/*.patch',
  './*.patch',
  '*.patch',
  './**/*.log',
  '**/*.log',
  './*.log',
  '*.log',
  './**/*.txt',
  '**/*.txt',
  './*.txt',
  '*.txt',
  './무림북_*/**/*',
  '무림북_*/**/*',
  './무명 무협소설/**/*',
  '무명 무협소설/**/*',
  './파이선 소설 이어쓰기/**/*',
  '파이선 소설 이어쓰기/**/*',
  './무명지협/**/*',
  '무명지협/**/*',
  './_temp_plan_*/**/*',
  '_temp_plan_*/**/*',
  './__pycache__/**/*',
  '__pycache__/**/*',
  './node_modules/{@next/swc-win32-x64-msvc}/**/*',
  'node_modules/{@next/swc-win32-x64-msvc}/**/*',
  './node_modules/{@next/swc-darwin-arm64}/**/*',
  'node_modules/{@next/swc-darwin-arm64}/**/*',
  './node_modules/{@next/swc-linux-x64-gnu}/**/*',
  'node_modules/{@next/swc-linux-x64-gnu}/**/*',
];

const nextConfig: any = {
  typescript: {
    ignoreBuildErrors: true,
  },
  async rewrites() {
    return {
      afterFiles: [
        {
          source: "/thumbnails/:path*",
          destination: "/api/thumbnails/:path*",
        },
      ],
    };
  },
  outputFileTracingExcludes: {
    '*': excludes,
    '**': excludes,
    '**/*': excludes,
    '/**/*': excludes,
    '/api/**/*': excludes,
    '/api/admin/automation/approve-plan': excludes,
    '/api/admin/automation/run': excludes,
  },
};

export default nextConfig;
