export const EMOJI_LIST = [
  { emoji: "🎁", label: "선물박스" },
  { emoji: "💰", label: "돈" },
  { emoji: "💎", label: "보석" },
  { emoji: "👑", label: "왕관" },
  { emoji: "🎉", label: "파티" },
  { emoji: "🍵", label: "찻잔" },
  { emoji: "📚", label: "책" },
  { emoji: "⚔️", label: "검" },
  { emoji: "🥋", label: "도복" },
  { emoji: "📜", label: "스크롤" },
  { emoji: "☯️", label: "태극" },
  { emoji: "🔔", label: "종" },
  { emoji: "📣", label: "확성기" },
  { emoji: "📢", label: "공지" },
  { emoji: "🔥", label: "불" },
  { emoji: "✨", label: "반짝" },
  { emoji: "🚀", label: "로켓" },
  { emoji: "⭐", label: "별" },
  { emoji: "💌", label: "편지" },
  { emoji: "💡", label: "아이디어" },
];
